// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List all assets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Asset"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Create an asset",
                "parameters": [
                    {
                        "description": "Asset input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateAssetInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "assets"
                ],
                "summary": "Delete all assets",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get aggregated asset summary (value, loans, equity)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AssetSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get an asset by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Update an asset (full replace)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateAssetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Asset"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "assets"
                ],
                "summary": "Delete an asset",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "List balance snapshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Balance"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Record a new point-in-time balance across all accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Create a balance snapshot",
                "parameters": [
                    {
                        "description": "Balance input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateBalanceInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Balance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances/allocation": {
            "get": {
                "description": "Returns percentage breakdown of the latest balance across accounts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Get current account allocation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AccountAllocation"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Get the latest balance snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Balance"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances/trend": {
            "get": {
                "description": "Returns time-series data suitable for charting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Get balance trend over time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.BalanceTrend"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balances/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Get balance by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Balance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Balance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balances"
                ],
                "summary": "Update a balance snapshot",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Balance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateBalanceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Balance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "balances"
                ],
                "summary": "Delete a balance snapshot",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Balance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/export/balances.csv": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export balance snapshots as CSV",
                "responses": {
                    "200": {
                        "description": "CSV file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/export/finances-partial.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export financial data since last full export as JSON",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.financeExport"
                        }
                    }
                }
            }
        },
        "/export/finances.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export all financial data as JSON for AI analysis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.financeExport"
                        }
                    }
                }
            }
        },
        "/export/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Get last export timestamps",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.exportStatus"
                        }
                    }
                }
            }
        },
        "/export/transactions.csv": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export transactions as CSV",
                "responses": {
                    "200": {
                        "description": "CSV file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/import/json": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "import"
                ],
                "summary": "Import financial data from a finances.json export file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "finances.json export file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.importResult"
                        }
                    }
                }
            }
        },
        "/insights": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insights"
                ],
                "summary": "List recent AI insights",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AIInsight"
                            }
                        }
                    }
                }
            }
        },
        "/insights/generate": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insights"
                ],
                "summary": "Generate a new AI financial insight",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.AIInsight"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/insights/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insights"
                ],
                "summary": "Get latest AI insight",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AIInsight"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "List all stock trades",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.StockTrade"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Create a stock trade",
                "parameters": [
                    {
                        "description": "Trade input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateStockTradeInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.StockTrade"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks/analyst/{ticker}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get analyst price targets from Yahoo Finance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticker symbol",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AnalystData"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks/history/{ticker}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get price history from Yahoo Finance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticker symbol",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Range: 1mo 3mo 6mo 1y 2y 5y (default 1y)",
                        "name": "range",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks/portfolio": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get computed stock portfolio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StockPortfolio"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks/price/{ticker}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get current stock price from Yahoo Finance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticker symbol",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stocks/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get a stock trade by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trade ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StockTrade"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Update a stock trade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trade ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateStockTradeInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StockTrade"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "stocks"
                ],
                "summary": "Delete a stock trade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trade ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "description": "Returns paginated, filtered transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "List transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Type: expense | income | investment",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PaginatedTransactions"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new expense, income, or investment record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a transaction",
                "parameters": [
                    {
                        "description": "Transaction input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateTransactionInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/summary": {
            "get": {
                "description": "Returns aggregated totals by type, category, and month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get transaction summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TransactionSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get a transaction by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Update a transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update input",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateTransactionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "transactions"
                ],
                "summary": "Delete a transaction",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AIInsight": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "domain.AccountAllocation": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount": {
                    "type": "number"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "domain.Asset": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current_value": {
                    "description": "latest valuation; defaults to purchase price",
                    "type": "number"
                },
                "equity": {
                    "description": "Computed for API response (not persisted)",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "loan_account": {
                    "description": "account payments are deducted from",
                    "type": "string"
                },
                "loan_paid_off_date": {
                    "type": "string"
                },
                "loan_rate": {
                    "description": "e.g. \"6M EURIBOR + 1.3%\"",
                    "type": "string"
                },
                "loan_remaining": {
                    "description": "Financing",
                    "type": "number"
                },
                "loan_remaining_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_price": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/domain.AssetType"
                },
                "updated_at": {
                    "type": "string"
                },
                "valuation_date": {
                    "type": "string"
                }
            }
        },
        "domain.AssetSummary": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "net_equity": {
                    "description": "total value − total loans",
                    "type": "number"
                },
                "total_loans": {
                    "type": "number"
                },
                "total_purchase_price": {
                    "type": "number"
                },
                "total_value": {
                    "type": "number"
                }
            }
        },
        "domain.AssetType": {
            "type": "string",
            "enum": [
                "vehicle",
                "real_estate",
                "solar",
                "other"
            ],
            "x-enum-varnames": [
                "AssetTypeVehicle",
                "AssetTypeRealEstate",
                "AssetTypeSolar",
                "AssetTypeOther"
            ]
        },
        "domain.Balance": {
            "type": "object",
            "properties": {
                "art": {
                    "description": "EUR",
                    "type": "number"
                },
                "btc_price": {
                    "description": "EUR/BTC rate at snapshot time (0 = legacy EUR row or price unknown)",
                    "type": "number"
                },
                "cash": {
                    "description": "EUR",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "ibkr_stocks": {
                    "description": "EUR - IBKR portfolio",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "luminor": {
                    "description": "EUR",
                    "type": "number"
                },
                "m_btc": {
                    "description": "stored in BTC units",
                    "type": "number"
                },
                "m_btc_eur": {
                    "description": "m_btc converted to EUR at live price",
                    "type": "number"
                },
                "r_btc": {
                    "description": "stored in BTC units",
                    "type": "number"
                },
                "r_btc_eur": {
                    "description": "Computed EUR values for BTC fields (not persisted, only set when holding \u003e 0)",
                    "type": "number"
                },
                "rev_m": {
                    "description": "EUR",
                    "type": "number"
                },
                "rev_r": {
                    "description": "EUR",
                    "type": "number"
                },
                "rev_stocks": {
                    "description": "EUR - Revolut stocks portfolio",
                    "type": "number"
                },
                "seb": {
                    "description": "EUR",
                    "type": "number"
                },
                "seb_pen": {
                    "description": "EUR",
                    "type": "number"
                },
                "swed": {
                    "description": "EUR",
                    "type": "number"
                },
                "swed_etf": {
                    "description": "EUR",
                    "type": "number"
                },
                "total": {
                    "description": "EUR - sum of all account balances",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.BalanceTrend": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "dates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totals": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "domain.Category": {
            "type": "string",
            "enum": [
                "Clothing",
                "Dating",
                "Divorce",
                "Entertainment",
                "Finance",
                "Food",
                "Gaming",
                "Gifts",
                "Health",
                "Housing",
                "Kids - Education",
                "Kids - Entertainment",
                "Kids - Food",
                "Kids - General",
                "Transport",
                "Vacation",
                "Salary",
                "Freelance",
                "Reimbursement",
                "Stocks \u0026 ETF",
                "Pension",
                "Crypto",
                "Real Estate"
            ],
            "x-enum-varnames": [
                "CategoryClothing",
                "CategoryDating",
                "CategoryDivorce",
                "CategoryEntertainment",
                "CategoryFinance",
                "CategoryFood",
                "CategoryGaming",
                "CategoryGifts",
                "CategoryHealth",
                "CategoryHousing",
                "CategoryKidsEducation",
                "CategoryKidsEntertainment",
                "CategoryKidsFood",
                "CategoryKidsGeneral",
                "CategoryTransport",
                "CategoryVacation",
                "CategorySalary",
                "CategoryFreelance",
                "CategoryReimbursement",
                "CategoryStocksETF",
                "CategoryPension",
                "CategoryCrypto",
                "CategoryRealEstate"
            ]
        },
        "domain.CategorySummary": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "count": {
                    "type": "integer"
                },
                "total": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/domain.TransactionType"
                }
            }
        },
        "domain.Currency": {
            "type": "string",
            "enum": [
                "EUR",
                "USD"
            ],
            "x-enum-varnames": [
                "CurrencyEUR",
                "CurrencyUSD"
            ]
        },
        "domain.Money": {
            "type": "object",
            "properties": {
                "currency": {
                    "$ref": "#/definitions/domain.Currency"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "domain.MonthlySummary": {
            "type": "object",
            "properties": {
                "expenses": {
                    "type": "number"
                },
                "income": {
                    "type": "number"
                },
                "investments": {
                    "type": "number"
                },
                "month": {
                    "type": "integer"
                },
                "month_name": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "domain.PaginatedTransactions": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Transaction"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "domain.StockAction": {
            "type": "string",
            "enum": [
                "buy",
                "sell"
            ],
            "x-enum-varnames": [
                "StockActionBuy",
                "StockActionSell"
            ]
        },
        "domain.StockHolding": {
            "type": "object",
            "properties": {
                "avg_cost": {
                    "description": "average cost per share",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                },
                "currency": {
                    "description": "currency of all Money fields below",
                    "type": "string"
                },
                "realized_gain": {
                    "description": "gain/loss from closed positions",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                },
                "shares": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "total_cost": {
                    "description": "total amount invested",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                }
            }
        },
        "domain.StockPortfolio": {
            "type": "object",
            "properties": {
                "holdings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.StockHolding"
                    }
                },
                "total_cost": {
                    "description": "sum of all holdings' cost basis",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                },
                "total_realized_gain": {
                    "description": "sum of all realized gains",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                }
            }
        },
        "domain.StockSource": {
            "type": "string",
            "enum": [
                "Revolut",
                "IBKR"
            ],
            "x-enum-varnames": [
                "StockSourceRevolut",
                "StockSourceIBKR"
            ]
        },
        "domain.StockTrade": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/domain.StockAction"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "description": "currency of PricePerShare",
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "price_per_share": {
                    "description": "Computed for API response (not persisted)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                },
                "shares": {
                    "type": "number"
                },
                "source": {
                    "$ref": "#/definitions/domain.StockSource"
                },
                "ticker": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Computed for API response (not persisted)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.Money"
                        }
                    ]
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "credit_account": {
                    "description": "CreditAccount is the account increased by this transaction (income: receiving account;\ntransfer/investment: destination). Empty = no account credited.",
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "debit_account": {
                    "description": "DebitAccount is the account decreased by this transaction (expense: paying account;\ntransfer/investment: funding source). Empty = no account debited.",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "source_account": {
                    "description": "Legacy field — kept for backward compat with existing rows. New rows use DebitAccount/CreditAccount.",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.TransactionType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.TransactionSummary": {
            "type": "object",
            "properties": {
                "by_category": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CategorySummary"
                    }
                },
                "by_month": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.MonthlySummary"
                    }
                },
                "net_balance": {
                    "type": "number"
                },
                "total_expenses": {
                    "type": "number"
                },
                "total_income": {
                    "type": "number"
                },
                "total_investments": {
                    "type": "number"
                }
            }
        },
        "domain.TransactionType": {
            "type": "string",
            "enum": [
                "expense",
                "income",
                "investment"
            ],
            "x-enum-varnames": [
                "TransactionTypeExpense",
                "TransactionTypeIncome",
                "TransactionTypeInvestment"
            ]
        },
        "handler.AnalystData": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "num_analysts": {
                    "type": "integer"
                },
                "recommendation": {
                    "type": "string"
                },
                "target_high": {
                    "type": "number"
                },
                "target_low": {
                    "type": "number"
                },
                "target_mean": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.assetExportRow": {
            "type": "object",
            "properties": {
                "current_value_eur": {
                    "type": "number"
                },
                "loan_account": {
                    "type": "string"
                },
                "loan_paid_off_date": {
                    "type": "string"
                },
                "loan_rate": {
                    "type": "string"
                },
                "loan_remaining_date": {
                    "type": "string"
                },
                "loan_remaining_eur": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "purchase_date": {
                    "type": "string"
                },
                "purchase_price_eur": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                },
                "valuation_date": {
                    "type": "string"
                }
            }
        },
        "handler.balExportRow": {
            "type": "object",
            "properties": {
                "art": {
                    "type": "number"
                },
                "btc_m": {
                    "type": "number"
                },
                "btc_price_eur": {
                    "type": "number"
                },
                "btc_r": {
                    "type": "number"
                },
                "cash": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "ibkr_stocks": {
                    "type": "number"
                },
                "luminor": {
                    "type": "number"
                },
                "revolut_m": {
                    "type": "number"
                },
                "revolut_r": {
                    "type": "number"
                },
                "revolut_stocks": {
                    "type": "number"
                },
                "seb": {
                    "type": "number"
                },
                "seb_pension": {
                    "type": "number"
                },
                "swed": {
                    "type": "number"
                },
                "swed_etf": {
                    "type": "number"
                },
                "total_eur": {
                    "type": "number"
                }
            }
        },
        "handler.exportStatus": {
            "type": "object",
            "properties": {
                "last_full_export": {
                    "type": "string"
                },
                "last_partial_export": {
                    "type": "string"
                }
            }
        },
        "handler.financeExport": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.assetExportRow"
                    }
                },
                "balances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.balExportRow"
                    }
                },
                "export_date": {
                    "type": "string"
                },
                "stock_trades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.stockExportRow"
                    }
                },
                "suggested_prompt": {
                    "type": "string"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.txExportRow"
                    }
                }
            }
        },
        "handler.importCounts": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "integer"
                },
                "balances": {
                    "type": "integer"
                },
                "stock_trades": {
                    "type": "integer"
                },
                "transactions": {
                    "type": "integer"
                }
            }
        },
        "handler.importResult": {
            "type": "object",
            "properties": {
                "imported": {
                    "$ref": "#/definitions/handler.importCounts"
                },
                "imported_tx_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "skipped": {
                    "$ref": "#/definitions/handler.importCounts"
                }
            }
        },
        "handler.stockExportRow": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price_per_share": {
                    "type": "number"
                },
                "shares": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "handler.txExportRow": {
            "type": "object",
            "properties": {
                "amount_eur": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "credit_account": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "debit_account": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "source_account": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.CreateAssetInput": {
            "type": "object",
            "required": [
                "name",
                "purchase_price",
                "type"
            ],
            "properties": {
                "current_value": {
                    "type": "number",
                    "minimum": 0
                },
                "loan_account": {
                    "type": "string"
                },
                "loan_paid_off_date": {
                    "type": "string"
                },
                "loan_rate": {
                    "type": "string"
                },
                "loan_remaining": {
                    "type": "number",
                    "minimum": 0
                },
                "loan_remaining_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "purchase_date": {
                    "description": "optional YYYY-MM-DD",
                    "type": "string"
                },
                "purchase_price": {
                    "type": "number"
                },
                "type": {
                    "enum": [
                        "vehicle",
                        "real_estate",
                        "solar",
                        "other"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.AssetType"
                        }
                    ]
                },
                "valuation_date": {
                    "type": "string"
                }
            }
        },
        "service.CreateBalanceInput": {
            "type": "object",
            "required": [
                "date"
            ],
            "properties": {
                "art": {
                    "type": "number"
                },
                "btc_price": {
                    "description": "EUR/BTC at snapshot time",
                    "type": "number"
                },
                "cash": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "ibkr_stocks": {
                    "type": "number"
                },
                "luminor": {
                    "type": "number"
                },
                "m_btc": {
                    "description": "BTC units",
                    "type": "number"
                },
                "r_btc": {
                    "description": "BTC units",
                    "type": "number"
                },
                "rev_m": {
                    "type": "number"
                },
                "rev_r": {
                    "type": "number"
                },
                "rev_stocks": {
                    "type": "number"
                },
                "seb": {
                    "type": "number"
                },
                "seb_pen": {
                    "type": "number"
                },
                "swed": {
                    "type": "number"
                },
                "swed_etf": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "service.CreateStockTradeInput": {
            "type": "object",
            "required": [
                "action",
                "date",
                "price_per_share",
                "shares",
                "source",
                "ticker"
            ],
            "properties": {
                "action": {
                    "enum": [
                        "buy",
                        "sell"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.StockAction"
                        }
                    ]
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price_per_share": {
                    "type": "number"
                },
                "shares": {
                    "type": "number"
                },
                "source": {
                    "enum": [
                        "Revolut",
                        "IBKR"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.StockSource"
                        }
                    ]
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "service.CreateTransactionInput": {
            "type": "object",
            "required": [
                "amount",
                "category",
                "date",
                "type"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "comment": {
                    "type": "string"
                },
                "credit_account": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "debit_account": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "expense",
                        "income",
                        "investment"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.TransactionType"
                        }
                    ]
                }
            }
        },
        "service.UpdateBalanceInput": {
            "type": "object",
            "properties": {
                "art": {
                    "type": "number"
                },
                "btc_price": {
                    "description": "EUR/BTC at snapshot time",
                    "type": "number"
                },
                "cash": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "ibkr_stocks": {
                    "type": "number"
                },
                "luminor": {
                    "type": "number"
                },
                "m_btc": {
                    "description": "BTC units",
                    "type": "number"
                },
                "r_btc": {
                    "description": "BTC units",
                    "type": "number"
                },
                "rev_m": {
                    "type": "number"
                },
                "rev_r": {
                    "type": "number"
                },
                "rev_stocks": {
                    "type": "number"
                },
                "seb": {
                    "type": "number"
                },
                "seb_pen": {
                    "type": "number"
                },
                "swed": {
                    "type": "number"
                },
                "swed_etf": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "service.UpdateStockTradeInput": {
            "type": "object",
            "properties": {
                "action": {
                    "enum": [
                        "buy",
                        "sell"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.StockAction"
                        }
                    ]
                },
                "currency": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price_per_share": {
                    "type": "number"
                },
                "shares": {
                    "type": "number"
                },
                "source": {
                    "enum": [
                        "Revolut",
                        "IBKR"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.StockSource"
                        }
                    ]
                },
                "ticker": {
                    "type": "string"
                }
            }
        },
        "service.UpdateTransactionInput": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "comment": {
                    "type": "string"
                },
                "credit_account": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "debit_account": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "expense",
                        "income",
                        "investment"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.TransactionType"
                        }
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Finance Tracker API",
	Description:      "Personal finance tracking API for expenses, income, investments and balance snapshots.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
